language: python
env:
  global:
    - CI=true

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.4
    - os: osx
      language: generic
      if: branch = master
  allow_failures:
    - os: osx
      language: generic

install:
    - chmod 700 ./travis/install.sh
    - ./travis/install.sh
    - pip3 --version

script:
    - py.test
    - make check
    - chmod 700 ./travis/test.sh
    - ./travis/test.sh

notifications:
    email: false
