language: node_js
node_js:
  - 8
env:
  global:
    - CI=true

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
    - os: osx
      language: generic
      if: branch = master
  allow_failures:
    - os: osx
      language: generic

install:
  - chmod 700 ./travis/install.sh
  - ./travis/install.sh

script:
  - npm run build
  - npm run test

notifications:
  email: false
