language: node_js
env:
  global:
    - CI=true

matrix:
  fast_finish: true
  include:
    - os: linux
    - os: osx
      language: generic
      if: branch = master
  allow_failures:
    - os: osx
      language: generic

install:
    - chmod 700 ./travis/install.sh
    - ./travis/install.sh

script:
    - chmod 700 ./travis/test.sh
    - ./travis/test.sh

notifications:
    email: false
