language: python
env:
  global:
    - CI=true

matrix:
  include:
    - os: linux
      python: 3.5
      addons:
        apt_packages:
          - pandoc
    - os: linux
      python: 3.4
      addons:
        apt_packages:
          - pandoc
    - os: osx
      language: generic

install:
    - chmod u+x travis/install.sh
    - travis/install.sh
    - pip3 --version

script:
    - py.test

notifications:
    email: false
